Trials number
gillout/MasterM pull request #10
Opened 2020-11-20 13:03 UTC by gillout

2020-11-20 16:04 UTC, matthieuaudemard commented
Prend tjs develop comme base pour tes nouvelles branches pas une branche features

2020-11-21 00:36 UTC, matthieuaudemard requested changes
Intéressante comme fonctionnalité. Essaye juste de revoir ta gestion d'erreur pour qu'elle soit toujours faite au même endroit (sinon on s'y retrouve plus).

2020-11-21 00:36 UTC, matthieuaudemard commented on ctrl/MastermindController.php
> +        if (!is_numeric($config->getValue('attempt'))) {
- fais une variable qui contient la valeur `$config->getValue('attempt')` pour éviter d'appeler 2 fois cette fonction
- vérifie que c'est un entier plutôt qu'un nombre

2020-11-21 00:36 UTC, matthieuaudemard commented on ctrl/MastermindController.php
> +            throw new Exception('Le nombre de tentatives doit être un nombre entier !');
Hmmm je trouve ça étrange de laisser la responsabilité au routeur de catch ton exception pour te rediriger.
Tu as une erreur, fais ta redirection ici. Je trouve ça plus correct.

2020-11-21 00:36 UTC, matthieuaudemard commented on ctrl/MastermindController.php
> +                $mastermind->setRemainingAttempts($attempt);
Alors je pense que tu devrais simplifier ton code. C'est pas forcément la solution la plus optimale, mais ça enlève un peu de complexité et permet de mieux gérer tes erreurs :
```php
public function start(Form $config): void {
    try {
        ...
        if (!is_int($config->getValue('attempt'))) {
            throw new Exception('Le nombre de tentatives doit être un nombre entier !');
        } elseif ($config->getValue('attempt') < 4 || $config->getValue('attempt') > 25) {
            throw new Exception('Le nombre de tentatives doit être compris entre 4 et 25 inclus !');
        }
        ...
        if ($duplicate || $size <= count(Mastermind::LEVELS[$level])) {
            ...
        } else {
            throw new Exception('Sans doublons, la taille de la solution doit être inférieure ou égale au nombre de couleurs possibles !');
        }
    } catch(Exception $e) {
           ErrorManager::add($e->getMessage§));
           header ('Location: index.php');
    }
}
```

2020-11-21 00:36 UTC, matthieuaudemard commented on router/Router.php
> +        }
Du coup avec la solution que je te propose tu n'as plus de gestion d'erreur à faire ici.

2020-11-21 00:36 UTC, matthieuaudemard commented on router/Router.php
>          $ctrl = new MastermindController();
Tu n'avais pas créé un MastermindController en propriété de ton router ?

2020-11-21 09:25 UTC, gillout commented on router/Router.php
>          $ctrl = new MastermindController();
Non, tu confonds avec book-store je pense.

2020-11-21 09:33 UTC, matthieuaudemard commented on router/Router.php
>          $ctrl = new MastermindController();
Ah oui c'est vrai 😄. Ben c'est l'occasion de le faire 😉

2020-11-21 09:48 UTC, matthieuaudemard requested changes
2 ptites modifs et puis c'est bon 😉

2020-11-21 09:48 UTC, matthieuaudemard commented on ctrl/MastermindController.php
> +            } else {
Ton `else` est superflu ici. Un `throw`, comme un `exit` ou un `return` va arrêter l'execution de ton programme donc tu peux te passer de mettre un `else`

2020-11-21 09:48 UTC, matthieuaudemard commented on router/Router.php
>          $ctrl = new MastermindController();
Du coup tu peux le mettre en propriété de ta classe vu que tu l'utilises dans chacune des fonctions de ton routeur

2020-11-21 12:16 UTC, matthieuaudemard requested changes
Essaye de tester ma proposition pour voir si ça marche 😉

2020-11-21 12:16 UTC, matthieuaudemard commented on ctrl/MastermindController.php
> +            $attempt = (int)$attempt;
Je pense que si dans ton `if` précédent tu vérifies `if (!is_int($attempt)) {...}` tu n'as plus besoin de faire ce cast en int.

2020-11-21 12:20 UTC, gillout commented on ctrl/MastermindController.php
> +            $attempt = (int)$attempt;
J'avais déjà testé mais en fait il considère dans tous les cas que ce n'est pas un int vu que cela vient de formulaire et que c'est string, c'est pour ça que j'ai fait ce que j'ai push. ;)

2020-11-21 12:26 UTC, matthieuaudemard approved these changes

2020-11-21 12:43 UTC, merged